import type { GeneratedFile } from "@prompt-guide/adapters";
import type { PromptGuideConfig } from "@prompt-guide/schema";

export function generateConfigToml(
  config: PromptGuideConfig,
): GeneratedFile[] {
  const lines: string[] = [
    "# Generated by prompt-guide — project-scoped Codex config",
    "# https://developers.openai.com/codex/config-reference",
    "",
    "project_doc_max_bytes = 65536",
    'project_doc_fallback_filenames = [".agents.md"]',
    "",
  ];

  for (const server of config.context.mcp_servers) {
    if (server.type === "http" && server.url) {
      lines.push(`[mcp_servers.${server.name}]`);
      lines.push('type = "http"');
      lines.push(`url = "${server.url}"`);
      if (server.auth_env) {
        lines.push("");
        lines.push(`[mcp_servers.${server.name}.headers]`);
        lines.push(`Authorization = "Bearer \${${server.auth_env}}"`);
      }
      lines.push("");
    } else if (server.type === "stdio" && server.command) {
      lines.push(`[mcp_servers.${server.name}]`);
      lines.push('type = "stdio"');
      lines.push(`command = "${server.command}"`);
      lines.push("");
    }
  }

  return [{ path: ".codex/config.toml", content: lines.join("\n") }];
}
