import fs from 'node:fs';
import path from 'node:path';
import chalk from 'chalk';
import { loadPromptConfig, type PromptConfig } from '../lib/load-config.js';
import { readPromptFromYaml } from '../lib/read-prompts.js';

const BAR = chalk.dim('  ' + '─'.repeat(44));

function writeCursorRules(cwd: string, config: PromptConfig, systemPrompt: string, reviewPrompt: string): void {
  const dir = path.join(cwd, '.cursor', 'rules');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const useConfigPath = path.join(dir, 'use-prompt-guide.mdc');
  const content = `---
description: Use this project's prompt.config.js and prompts/ (single source of truth)
alwaysApply: true
---

<!-- Generated by prompt-guide install. You do NOT need to re-run install when you change prompt.config.js or prompts/ — the AI reads those files. Re-run install only when you change \`tool\`. Do not edit this file by hand. -->

# Use project prompt config (single source of truth)

This project uses **prompt-guide**. All rules and behavior come from **\`prompt.config.js\`** and the YAML in **\`prompts/\`**. This file only tells you to read them.

- **Always read** \`prompt.config.js\` first. Then read **all YAML in \`prompts/\`** that the config points to (e.g. \`prompts.default\`, \`prompts.review\`, \`taskPresets.*.prompt\`) and any other \`.yml\` in \`prompts/\` that may define rules. Do not assume a fixed list — the user may add new files.
- When the user asks about project behavior, coding standards, review criteria, task presets, or platform: **load and apply** what you find in those files. Prefer them over generic advice.
- After you change \`prompt.config.js\` or add/edit files in \`prompts/\`, no further step is needed — the next chat will use the updated content when you read the files.
`;
  fs.writeFileSync(useConfigPath, content);
}

function writeCodexAgentsMd(cwd: string, systemPrompt: string, reviewPrompt: string): void {
  const filePath = path.join(cwd, 'AGENTS.md');
  const intro = `# Prompt Guide — project rules

This project uses prompt-guide. Full config: \`prompt.config.js\` and \`prompts/*.yml\`.
Below: system core and review criteria (concise). Do not exceed ~32 KiB total.

---

## System core (required rules)

`;
  const core = systemPrompt.length > 12000 ? systemPrompt.slice(0, 12000) + '\n\n...(see prompts/system.core.yml for full text)' : systemPrompt;
  const reviewSection = `

---

## Review criteria

`;
  const review = reviewPrompt.length > 8000 ? reviewPrompt.slice(0, 8000) + '\n\n...(see prompts/review.yml for full)' : reviewPrompt;
  const full = intro + core + reviewSection + review;
  fs.writeFileSync(filePath, full);
}

function writeWindsurfRules(cwd: string, systemPrompt: string): void {
  const filePath = path.join(cwd, '.windsurfrules');
  const maxLen = 6000;
  const condensed = systemPrompt.replace(/\n{2,}/g, '\n').slice(0, maxLen - 200);
  const content = `# Prompt Guide — rules (from prompt.config.js / prompts)
# Edit prompt.config.js and run \`prompt-guide install\` to regenerate.

${condensed}${systemPrompt.length > maxLen - 200 ? '\n\n...(truncated; see prompts/system.core.yml)' : ''}
`;
  fs.writeFileSync(filePath, content);
}

function writeClaudeRules(cwd: string, systemPrompt: string, reviewPrompt: string): void {
  const dir = path.join(cwd, '.claude', 'rules');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const corePath = path.join(dir, 'prompt-guide-core.md');
  fs.writeFileSync(corePath, `# System core (prompt-guide)\n\n${systemPrompt}`);

  const reviewPath = path.join(dir, 'prompt-guide-review.md');
  fs.writeFileSync(reviewPath, `# Review criteria (prompt-guide)\n\n${reviewPrompt}`);
}

export type InstallOptions = { dryRun?: boolean; verbose?: boolean };

export function runInstall(options: InstallOptions = {}): void {
  const { dryRun = false } = options;
  const cwd = process.cwd();

  const config = loadPromptConfig(cwd);
  const tool = (config.tool || 'cursor').toLowerCase();

  const defaultPath = config.prompts?.default ?? 'prompts/system.core.yml';
  const reviewPath = config.prompts?.review ?? 'prompts/review.yml';

  let systemPrompt: string;
  let reviewPrompt: string;
  try {
    systemPrompt = readPromptFromYaml(cwd, defaultPath);
    reviewPrompt = readPromptFromYaml(cwd, reviewPath);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to read prompts: ${message}`);
  }

  if (dryRun) {
    console.log(chalk.dim('  [dry-run] Would install for tool: ') + chalk.cyan(tool));
    console.log(BAR);
    if (tool === 'cursor') console.log(chalk.blue('  →') + ' .cursor/rules/use-prompt-guide.mdc');
    if (tool === 'codex') console.log(chalk.blue('  →') + ' AGENTS.md');
    if (tool === 'windsurf') console.log(chalk.blue('  →') + ' .windsurfrules');
    if (tool === 'claude') console.log(chalk.blue('  →') + ' .claude/rules/prompt-guide-*.md');
    if (tool === 'other') console.log(chalk.dim('  → No tool-specific files (tool=other). Use prompt.config.js as reference.'));
    console.log(BAR);
    return;
  }

  switch (tool) {
    case 'cursor':
      writeCursorRules(cwd, config, systemPrompt, reviewPrompt);
      console.log(chalk.green('  ✓') + ' .cursor/rules/use-prompt-guide.mdc');
      console.log(chalk.dim('  → 설정은 prompt.config.js, prompts/ 만 수정하세요. 다시 install 할 필요 없습니다 (tool 바꿀 때만).'));
      break;
    case 'codex':
      writeCodexAgentsMd(cwd, systemPrompt, reviewPrompt);
      console.log(chalk.green('  ✓') + ' AGENTS.md');
      console.log(chalk.dim('  → 설정 바꾼 뒤엔 다시 prompt-guide install 하세요.'));
      break;
    case 'windsurf':
      writeWindsurfRules(cwd, systemPrompt);
      console.log(chalk.green('  ✓') + ' .windsurfrules');
      console.log(chalk.dim('  → 설정 바꾼 뒤엔 다시 prompt-guide install 하세요.'));
      break;
    case 'claude':
      writeClaudeRules(cwd, systemPrompt, reviewPrompt);
      console.log(chalk.green('  ✓') + ' .claude/rules/prompt-guide-core.md, prompt-guide-review.md');
      console.log(chalk.dim('  → 설정 바꾼 뒤엔 다시 prompt-guide install 하세요.'));
      break;
    default:
      console.log(chalk.dim('  · tool=') + chalk.cyan(tool) + chalk.dim(' — no tool-specific files. Edit prompt.config.js and use it as reference.'));
  }
}
