import fs from 'node:fs';
import path from 'node:path';
import chalk from 'chalk';
import {
  loadPromptConfig,
  getLayersSource,
  getLayersManifestPath,
  getBundleMinify,
  getDocsAuthoringRoot,
  type PromptConfig,
} from '../lib/load-config.js';
import { syncDocsAuthoringToLayerTargets } from '../lib/sync-docs-to-layers.js';
import { minifyMarkdownForBundle } from '../lib/bundle-text.js';
import { DEFAULT_LAYERS_MANIFEST } from '../lib/layer-paths.js';
import { readPromptFromYaml } from '../lib/read-prompts.js';
import { tryBuildPromptsFromAi, hasAiHierarchy, listAiMarkdownFiles } from '../lib/read-ai-layered.js';

const BAR = chalk.dim('  ' + '─'.repeat(44));
const CODEC_AGENTS_MAX_BYTES = 32 * 1024;
const WINDSURF_MAX_CHARS = 6000;

function writeCursorRules(
  cwd: string,
  config: PromptConfig,
  _systemPrompt: string,
  _reviewPrompt: string,
  layersManifestPath: string
): void {
  const dir = path.join(cwd, '.cursor', 'rules');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const layersSource = getLayersSource(config);
  const manifestRel =
    path.relative(cwd, layersManifestPath).split(path.sep).join('/') || DEFAULT_LAYERS_MANIFEST;
  const useConfigPath = path.join(dir, 'use-prompt-guide.mdc');
  const content = `---
description: prompt-guide — layered AI context + prompt.config.js + prompts/
alwaysApply: true
---

<!-- Generated by prompt-guide install. Re-run install when you change \`tool\`. Edit \`${layersSource}/\`, \`prompt.config.js\`, or \`prompts/\` directly — no reinstall needed for content changes. -->

# Project AI context (prompt-guide)

## 1. Config

Read **\`prompt.config.js\`** first (\`tool\`, \`stackProfile\`, \`context.include\`, task presets, \`layers.source\`, \`layers.manifest\`, \`layers.bundleMinify\`).

## 1b. Merge manifest (\`${manifestRel}\`)

This file defines **which layer files** (\`.md\` or YAML with \`prompt:\` / \`text:\`) are concatenated (in order) for Codex / Claude / Windsurf bundles, and **\`review.path\`** for review mode. Edit **\`system:\`** to add new layers (paths are relative to \`layers.source\`). Set **\`cursor.list: system\`** to make the Cursor manifest list only those files; **\`all\`** lists every \`.md\` / \`.yml\` / \`.yaml\` under \`layers.source\`.

## 2. Layered context (\`${layersSource}/\`)

**These files are normal workspace files.** You can and **must** read them with your file tools when answering anything about standards, product, or process for this repo.

**\`prompt-guide init\`** copies the same template to **\`.cursor/\`**, **\`.claude/\`**, **\`codex/\`**, **\`.windsurf/\`** (each has \`core/\`, \`context/\`, … at that root — **no** \`…/ai/\` folder). Set **\`layers.source\`** to the tree \`install\` should use when bundling; keep copies in sync if you edit more than one.

**Note:** Structured context is **not** the same as \`.cursor/rules/\` (Cursor Rules, \`.mdc\`). Bundled Claude outputs from \`install\` are under \`.claude/rules/ai-*.md\`.

**Companion rule:** \`read-ai-context-manifest.mdc\` lists layer files per \`layers.manifest.yml\`: \`cursor.list: all\` → every \`.md\` / \`.yml\` / \`.yaml\` under \`${layersSource}/\`; \`system\` → only paths in \`system:\` plus \`review.path\`. Follow that list so nothing is skipped.

Treat \`${layersSource}/\` as the **primary** structured context. **Do not collapse layers:**

| Layer | Role |
|-------|------|
| **\`core/\`** | Non-negotiable rules, constraints, style. |
| **\`context/\`** | Product, architecture, domain — **what** the system is. |
| **\`memory/\`** | Decisions, patterns, bugs — **what we already know**. |
| **\`actions/\`** | Coding / debugging / reviewing — **how to work** for that mode. |
| **\`agents/\`** | Specialist overlays (e.g. service, client, operations) when the task matches. |
| **\`runtime/\`** | **Session execution context** — \`task.md\`, \`plan.md\` for *this* session when in use. |

**Default read order:** \`core/\` → \`context/\` → \`memory/\` → relevant \`actions/\` → relevant \`agents/\` → \`runtime/\` when applicable. See **\`${layersSource}/README.md\`**.

## 3. \`.cursorignore\`

**Do not** add \`${layersSource}/\` to \`.cursorignore\` (or any ignore that blocks the AI from reading project rules). If you use broad ignore patterns, **allowlist** \`${layersSource}/**\`.

## 4. YAML (\`prompts/\`)

Use \`prompts/*.yml\` from \`prompt.config.js\` when needed (presets, platform YAML, or gaps). Prefer \`${layersSource}/\` + config over generic advice.

## 5. Optional stack rules pack

If \`prompt.config.js\` sets \`stackProfile\` (or legacy \`platform\`), merge **\`prompts/rules.by-platform.yml\`** for that key after core rules.
`;
  fs.writeFileSync(useConfigPath, content);

  writeCursorAiManifest(cwd, layersSource, layersManifestPath);
}

function writeCursorAiManifest(cwd: string, layersRoot: string, layerManifestPath: string): void {
  if (!hasAiHierarchy(cwd, layersRoot)) return;

  const dir = path.join(cwd, '.cursor', 'rules');
  const paths = listAiMarkdownFiles(cwd, layersRoot, layerManifestPath);
  if (paths.length === 0) return;

  const lines = paths.map((p, i) => `${i + 1}. \`${p}\``).join('\n');
  const manifestPath = path.join(dir, 'read-ai-context-manifest.mdc');
  const body = `---
description: MUST read these layered context files — explicit paths for agents (prompt-guide)
alwaysApply: true
---

# Read all layered context files (\`${layersRoot}/\`)

**MUST:** For any task that touches this repo’s rules, product, architecture, or review standards, **open and read every path below** (in order) using your file-reading tool. Relying on memory or search snippets alone is **not** enough.

**Why:** Some UIs do not auto-index dot-directories; an explicit list guarantees coverage.

## Files (read in order)

${lines}

---

After reading, apply layers as described in \`use-prompt-guide.mdc\` and \`${layersRoot}/README.md\`.
`;
  fs.writeFileSync(manifestPath, body);
}

function writeCodexAgentsMd(
  cwd: string,
  systemPrompt: string,
  reviewPrompt: string,
  layersSource: string,
  bundleMinify: boolean
): void {
  const filePath = path.join(cwd, 'AGENTS.md');
  const intro = `# Prompt Guide — project rules

This project uses prompt-guide. Layered Markdown: \`${layersSource}/\` (and mirrors under \`.cursor/\`, \`.claude/\`, \`codex/\`, \`.windsurf/\` from \`init\` — no \`/ai/\` subfolder). Full config: \`prompt.config.js\`. Fallback YAML: \`prompts/*.yml\`.
Below: bundled rules (from \`layers.source\` or YAML). Do not exceed ~32 KiB total.

---
`;
  let core = systemPrompt;
  let review = reviewPrompt;
  if (bundleMinify) {
    core = minifyMarkdownForBundle(core);
    review = minifyMarkdownForBundle(review);
  }
  core = core.length > 12000 ? core.slice(0, 12000) + '\n\n...(see prompts/system.core.yml for full text)' : core;
  review = review.length > 8000 ? review.slice(0, 8000) + '\n\n...(see prompts/review.yml for full)' : review;
  let full = intro + core + '\n\n---\n\n' + review;
  if (Buffer.byteLength(full, 'utf8') > CODEC_AGENTS_MAX_BYTES) {
    full = full.slice(0, CODEC_AGENTS_MAX_BYTES - 80) + '\n\n...(truncated to fit Codex ~32 KiB limit)';
  }
  fs.writeFileSync(filePath, full);
}

function writeWindsurfRules(
  cwd: string,
  systemPrompt: string,
  layersSource: string,
  bundleMinify: boolean
): void {
  const filePath = path.join(cwd, '.windsurfrules');
  const note = `Regenerate: prompt-guide install. Edit ${layersSource}/, prompt.config.js, prompts/.\n\n`;
  const reserved = note.length + 60;
  let body = bundleMinify ? minifyMarkdownForBundle(systemPrompt) : systemPrompt;
  body = body.replace(/\n{2,}/g, '\n');
  const condensed = body.slice(0, WINDSURF_MAX_CHARS - reserved);
  const content =
    note +
    condensed +
    (body.length > WINDSURF_MAX_CHARS - reserved ? `\n\n...(truncated; see ${layersSource}/ or prompts/)` : '');
  fs.writeFileSync(filePath, content);
}

function writeClaudeRules(
  cwd: string,
  systemPrompt: string,
  reviewPrompt: string,
  bundleMinify: boolean
): void {
  const dir = path.join(cwd, '.claude', 'rules');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const core = bundleMinify ? minifyMarkdownForBundle(systemPrompt) : systemPrompt;
  const review = bundleMinify ? minifyMarkdownForBundle(reviewPrompt) : reviewPrompt;

  const corePath = path.join(dir, 'ai-core.md');
  fs.writeFileSync(corePath, core);

  const reviewPath = path.join(dir, 'ai-review.md');
  fs.writeFileSync(reviewPath, review);
}

export type InstallOptions = { dryRun?: boolean; verbose?: boolean };

export function runInstall(options: InstallOptions = {}): void {
  const { dryRun = false } = options;
  const cwd = process.cwd();

  const config = loadPromptConfig(cwd);
  const tool = (config.tool || 'cursor').toLowerCase();

  const defaultPath = config.prompts?.default ?? 'prompts/system.core.yml';
  const reviewPath = config.prompts?.review ?? 'prompts/review.yml';
  const layersSource = getLayersSource(config);
  const layersManifestPath = getLayersManifestPath(cwd, config);
  const bundleMinify = getBundleMinify(config);

  if (!dryRun) {
    const syncResult = syncDocsAuthoringToLayerTargets(cwd, config);
    if (!syncResult.skipped && syncResult.files > 0) {
      console.log(
        chalk.dim('  →') +
          ' synced ' +
          chalk.cyan(String(syncResult.files)) +
          ' Markdown file(s) → YAML × ' +
          String(syncResult.targets) +
          ' layer root(s)'
      );
    }
  } else {
    const authorRoot = getDocsAuthoringRoot(config);
    if (authorRoot && fs.existsSync(path.join(cwd, authorRoot))) {
      console.log(
        chalk.dim('  [dry-run] Would sync ') +
          chalk.cyan(authorRoot) +
          chalk.dim('/ → *.yml under layer roots, then bundle.')
      );
    }
  }

  let systemPrompt: string;
  let reviewPrompt: string;
  try {
    const layered = tryBuildPromptsFromAi(cwd, layersSource, layersManifestPath);
    if (layered) {
      systemPrompt = layered.system;
      reviewPrompt = layered.review || readPromptFromYaml(cwd, reviewPath);
    } else {
      systemPrompt = readPromptFromYaml(cwd, defaultPath);
      reviewPrompt = readPromptFromYaml(cwd, reviewPath);
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to read prompts: ${message}`);
  }

  if (dryRun) {
    console.log(chalk.dim('  [dry-run] Would install for tool: ') + chalk.cyan(tool));
    console.log(BAR);
    if (tool === 'cursor') {
      console.log(chalk.blue('  →') + ' .cursor/rules/use-prompt-guide.mdc');
      console.log(chalk.blue('  →') + ' .cursor/rules/read-ai-context-manifest.mdc (if layered tree present)');
    }
    if (tool === 'codex') console.log(chalk.blue('  →') + ' AGENTS.md');
    if (tool === 'windsurf') console.log(chalk.blue('  →') + ' .windsurfrules');
    if (tool === 'claude') console.log(chalk.blue('  →') + ' .claude/rules/ai-*.md');
    if (tool === 'other') console.log(chalk.dim('  → No tool-specific files (tool=other). Use prompt.config.js as reference.'));
    console.log(BAR);
    return;
  }

  const verbose = options.verbose === true;

  switch (tool) {
    case 'cursor':
      writeCursorRules(cwd, config, systemPrompt, reviewPrompt, layersManifestPath);
      console.log(chalk.green('  ✓') + ' .cursor/rules/use-prompt-guide.mdc');
      if (hasAiHierarchy(cwd, layersSource)) {
        console.log(chalk.green('  ✓') + ' .cursor/rules/read-ai-context-manifest.mdc');
      }
      if (verbose) {
        console.log(chalk.dim('    ') + path.join(cwd, '.cursor', 'rules', 'use-prompt-guide.mdc'));
        if (hasAiHierarchy(cwd, layersSource)) {
          console.log(chalk.dim('    ') + path.join(cwd, '.cursor', 'rules', 'read-ai-context-manifest.mdc'));
        }
      }
      console.log(
        chalk.dim('  → Edit ') +
          chalk.cyan('docs/prompt-guide/**/*.md') +
          chalk.dim(', ') +
          chalk.cyan('prompt.config.js') +
          chalk.dim(', prompts/. Re-run install when you change prompts or tool.')
      );
      break;
    case 'codex':
      writeCodexAgentsMd(cwd, systemPrompt, reviewPrompt, layersSource, bundleMinify);
      console.log(chalk.green('  ✓') + ' AGENTS.md');
      if (verbose) console.log(chalk.dim('    ') + path.join(cwd, 'AGENTS.md'));
      console.log(chalk.dim('  → Re-run prompt-guide install after changing config.'));
      break;
    case 'windsurf':
      writeWindsurfRules(cwd, systemPrompt, layersSource, bundleMinify);
      console.log(chalk.green('  ✓') + ' .windsurfrules');
      if (verbose) console.log(chalk.dim('    ') + path.join(cwd, '.windsurfrules'));
      console.log(chalk.dim('  → Re-run prompt-guide install after changing config.'));
      break;
    case 'claude':
      writeClaudeRules(cwd, systemPrompt, reviewPrompt, bundleMinify);
      console.log(chalk.green('  ✓') + ' .claude/rules/ai-core.md, ai-review.md');
      if (verbose) {
        console.log(chalk.dim('    ') + path.join(cwd, '.claude', 'rules', 'ai-core.md'));
        console.log(chalk.dim('    ') + path.join(cwd, '.claude', 'rules', 'ai-review.md'));
      }
      console.log(chalk.dim('  → Re-run prompt-guide install after changing config.'));
      break;
    default:
      console.log(chalk.dim('  · tool=') + chalk.cyan(tool) + chalk.dim(' — no tool-specific files. Edit prompt.config.js and use it as reference.'));
  }
}
